version: '3'

services:
  # Servidor PHP con Apache
  php_apache_server:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile
      args:
        PROJECT_PATH: ${PROJECT_PATH}
    container_name: php-apache
    ports:
      - "${PHP_APACHE_PORT}:80"
    volumes:
      - ${PROJECT_PATH}:/var/www/html
    command: >
      apache2-foreground

  mysql:
    image: mysql:latest
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${COMPOSE_PROJECT_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql/sql:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql:rw

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

volumes:
  persistent:
