version: '3'

services:
  # Servidor PHP con Apache
  php_apache_server:
    build:
      context: ./
      dockerfile: dockerfile/Dockerfile
    container_name: php-apache
    ports:
      - "${PHP_APACHE_PORT}:80"
    volumes:
      - ${PROJECT_PATH}:/var/www/html
      - ./docker.conf:${PROJECT_PATH}dockerfile/Dockerfile/hostvitrual/docker.conf
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command: >
      bash -c "a2ensite docker.conf && apache2-foreground"
               
  # Servidor MySQL
  mysql:
    image: mysql:latest
    ports:
     - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${COMPOSE_PROJECT_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
        - ./mysql/sql:/docker-entrypoint-initdb.d
        - persistent:/var/lib/mysql:rw

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

# Volúmenes definidos
volumes:
  persistent:
