services:
  php_apache_finanzashogar:
    build:
      context: .
      dockerfile: ./php_server/Dockerfile
      args:
        NEW_UID: ${NEW_UID}
        NEW_GID: ${NEW_GID}
        MY_USER: ${MY_USER}
        MY_GROUP: ${MY_GROUP}
    container_name: php_apache_finanzashogar
    ports:
      - "${PHP_APACHE_PORT}:80"
    volumes:
      - ../.:/var/www/html
    networks:
      - network_finanzashogar

  mysql:
    image: mysql:latest
    container_name: mysql-finanzashogar
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT: ${MYSQL_ROOT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - persistent-finanzashogar:/var/lib/mysql:rw
    depends_on:
      - php_apache_finanzashogar
    networks:
    - network_finanzashogar

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-finanzashogar
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
    - network_finanzashogar

networks:
  network_finanzashogar:  
    name: network_finanzashogar

volumes:
  persistent-finanzashogar:
